# Generated by Django 3.2.8 on 2021-11-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='Follower',
            new_name='follower',
        ),
    ]
