# Generated by Django 3.2.8 on 2021-11-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_rename_follower_followers_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
