# Generated by Django 3.2.8 on 2021-11-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20211114_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='number_of_likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
